# uncomment below to enable mtls
#server:
#  ssl:
#    enabled: true
#    client-auth: need
#    key-store: classpath:user-key-store.jks
#    key-store-password: secret
#    key-alias: user-server
#    key-store-type: JKS
#    key-store-provider: SUN
#    trust-store: classpath:user-trust-store.jks
#    trust-store-password: secret
#    trust-store-type: JKS


#spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
#spring.datasource.username=${DATABASE_USERNAME:root}
#spring.datasource.password=${DATABASE_PASSWORD:root}
#spring.jpa.show-sql=${JPA_SHOW_SQL:true}
#spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: elk
    password: cQ57ZWKm5WLSM!q#5^2&
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true